### ISSUE TITLE
Saving Dictionary Order

### ISSUE THREAD

**Issue by chrisaxiom** [extjwnl/extjwnl#12]
Hello,

Thank you for writing this library.  I am looking to use it to add synsets and then saving the results in wordnet format.  When I do add a synset and save it, there are two issues.

1. The new sysnet is 1st in the file (i.e. in `data.noun`) instead of last (thus all previous ID's will be changed).  I wish to keep all previous IDs the same and append the new sysnets to the end of the file - is this possible?
2. The saved files no longer keep the comments at the beginnings of the files.  For example, the 1st synset in the original wordnet 3.0/3.1 `data.noun` file has the offset 1740, as there is 1740 characters of comments in the file before the 1st synset entry.  This code will not write the comments, thus it will change every synsets offset, which is not desirable for me.

Before I go and start hacking the code, do you know if there was some reason for these choices or was it simply arbitrary?

Thanks,
Chris.

**Comment by autayeu** [comment]
Hi Chris.

1) Can you tell me in details how do you do that so I'll try to reproduce?
2) Take a look at the PrincetonRandomAccessDictionaryFile options in the [file_properties.xml configuration file](https://github.com/extjwnl/extjwnl/blob/master/extjwnl/src/main/resources/net/sf/extjwnl/dictionary/file_properties.xml). There is an option ```write_princeton_header```, which is commented out by default:
```xml
<!--<param name="write_princeton_header" value="true"/>-->
```
Uncomment it and the header should be preserved. 

Let me know if 2) works for you and let me know about 1). Thank you.

Aliaksandr

**Comment by chrisaxiom** [comment]
Hi Aliaksandr!

Here is the code for 1. that I am using:

```
Dictionary dictionary = Dictionary.getFileBackedInstance("/data/dict");
System.out.println("Version: " + dictionary.getVersion());
dictionary.edit();
Synset newSynset = new Synset(dictionary, POS.NOUN);
newSynset.setGloss("Someone who rides a bobsleigh  ");
dictionary.addSynset(newSynset);
IndexWord newWord = new IndexWord(dictionary, "bobsledder", POS.NOUN, newSynset);
dictionary.addIndexWord(newWord);
// get existing sledder
Synset sledder = dictionary.getSynsetAt(POS.NOUN, 10629849);
// make bobsledder a kind of sledder
Pointer newPointer = new Pointer(PointerType.HYPONYM, sledder, newSynset);
sledder.getPointers().add(newPointer);
dictionary.save();
System.out.println("saving done");
```

The new `data.noun` file will have the entry "bobsledder" at the top with offset 0000000.  Perhaps I need to set the offset manually?

For 2. I will try that, thanks!

**Comment by chrisaxiom** [comment]
2. that worked, thanks! (I am surprised that the version is not dynamically computed however.)

For 1, if I set the offset manually (`newSynset.setOffset()) I can get it to the end of the file but not with the correct offset (it seems to ignore what I put in other than it being greater the last synset offset.  It ends up being 15 off of what it should be.)  I will trace it through to see if I can figure out whats going on.

**Comment by chrisaxiom** [comment]
In my journey I found why the offsets are different. Added it as a new issue!

**Comment by chrisaxiom** [comment]
Going to close this issue, as it appears to be doing the right thing with the offsets other than the bug.
