### ISSUE TITLE
Loading from file is not Idempotent

### ISSUE THREAD

**Issue by chrisaxiom** [extjwnl/extjwnl#13]
Mistakenly, some glosses in the 3.1 and 3.0 dictionaries will begin with a space.  The `CharSequenceTokenizer` class will skip this leading space when calling `.skip()` on the `|` character.  Thus, all offsets will progressively get out of sync with the original file as they are loaded slightly differently.

See here: https://github.com/extjwnl/extjwnl/blob/c33cf88bc43dfb3a4afdf457d70599b4e525ab9b/extjwnl/src/main/java/net/sf/extjwnl/princeton/data/AbstractPrincetonFileDictionaryElementFactory.java#L131

**Comment by autayeu** [comment]
I know about this. When implementing this, I wasn't sure one should really repeat all the... lets call them peculiarities, as well. But maybe for backwards compatibility one might. I don't know. As you write, the glosses *mistakenly* begin with a space. Besides, it's not the only issue there, I vaguely recall there was something else of similar nature, like repeated pointer.

In addition, why changing offsets is a problem? Perhaps you use them as keys? It's better to use sense key as key, not offsets. Sense keys should not change between WordNet releases and vocabulary changes. However, offsets are faster than sense keys. 

Anyway, what would you propose doing?

**Comment by chrisaxiom** [comment]
Yea I really don't like working with offsets as IDs/keys, but unfortunately all the additional resources I am working with reference the offsets, so I need to make sure that the offsets don't change or change as little as possible.  I just changed it in my fork to manually skip over the `|` symbol as a quick fix for now.  

I am not sure what would be the proper "fix" other than perhaps an option to "preserve_peculiarities" :)

**Comment by chrisaxiom** [comment]
Just FYI with wordnet 3.1 data files with the space prefix fix its appears to be idempotent again....

**Comment by autayeu** [comment]
Thank you for the update.
