### ISSUE TITLE
NumberFormatException when running net.sf.extjwnl.utilities.Examples.java

### ISSUE THREAD

**Issue by tbuell26** [extjwnl/extjwnl#16]
I am trying to run the extjwnl Examples.java but I keep receving the following error. I amusing WordNet 3.1

Base form for "running-away": [IndexWord: [Lemma: run away] [POS: verb]]
Exception in thread "main" java.lang.NumberFormatException: For input string: "cordiality;"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at net.sf.extjwnl.util.TokenizerParser.nextLong(TokenizerParser.java:51)
	at net.sf.extjwnl.princeton.data.AbstractPrincetonFileDictionaryElementFactory.createSynset(AbstractPrincetonFileDictionaryElementFactory.java:58)
	at net.sf.extjwnl.dictionary.FileBackedDictionary.getSynset(FileBackedDictionary.java:195)
	at net.sf.extjwnl.dictionary.FileBackedDictionary.getSynsetAt(FileBackedDictionary.java:184)
	at net.sf.extjwnl.data.IndexWord$SynsetList.loadSynset(IndexWord.java:408)
	at net.sf.extjwnl.data.IndexWord$SynsetList.loadAllSynsets(IndexWord.java:389)
	at net.sf.extjwnl.data.IndexWord$SynsetList.get(IndexWord.java:113)
	at net.sf.extjwnl.data.IndexWord$SynsetList.get(IndexWord.java:43)
	at cobra.analytics.wikipedia.batch.Examples.demonstrateSymmetricRelationshipOperation(Examples.java:110)
	at cobra.analytics.wikipedia.batch.Examples.go(Examples.java:70)
	at cobra.analytics.wikipedia.batch.Examples.main(Examples.java:44)

**Comment by autayeu** [comment]
Thank you for reporting. I can't reproduce this.

If you can give specific details on how to reproduce this, please, reopen. Thank you.

**Comment by tbuell26** [comment]
I modified your Examples.java class to try and retrieve synsnets for certain words and I'm still getting the error.

public class Examples {
	private static final String USAGE = "Usage: Examples [properties file]";
    private static final Set<String> HELP_KEYS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(
            "--help", "-help", "/help", "--?", "-?", "?", "/?"
    )));

    public static void main(String[] args) throws FileNotFoundException, JWNLException, CloneNotSupportedException {
        Dictionary dictionary = null;
        if (args.length != 1) {
            dictionary = Dictionary.getDefaultResourceInstance();
        } else {
            if (HELP_KEYS.contains(args[0])) {
                System.out.println(USAGE);
            } else {
                FileInputStream inputStream = new FileInputStream(args[0]);
                dictionary = Dictionary.getInstance(inputStream);
            }
        }

        if (null != dictionary) {
            new Examples(dictionary).go();
        }
    }

 
    private IndexWord FUNNY;
      private final Dictionary dictionary;

    public Examples(Dictionary dictionary) throws JWNLException {
        this.dictionary = dictionary;
     
        FUNNY = dictionary.lookupIndexWord(POS.ADJECTIVE, "funny");
       
    }

    public void go() throws JWNLException, CloneNotSupportedException {
       
        demonstrateSynsets(FUNNY);
       
    }
    
  

       private void demonstrateSynsets(IndexWord word) {
    	List<Synset> syns = word.getSenses(); 
    	for (Synset syn : syns) {
    		System.out.println(" The gloss is " + syn.getGloss());
    	}
    }

 
    
}
The exception is 
Exception in thread "main" java.lang.NumberFormatException: For input string: "cordiality;"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at net.sf.extjwnl.util.TokenizerParser.nextLong(TokenizerParser.java:51)
	at net.sf.extjwnl.princeton.data.AbstractPrincetonFileDictionaryElementFactory.createSynset(AbstractPrincetonFileDictionaryElementFactory.java:58)
	at net.sf.extjwnl.dictionary.FileBackedDictionary.getSynset(FileBackedDictionary.java:195)
	at net.sf.extjwnl.dictionary.FileBackedDictionary.getSynsetAt(FileBackedDictionary.java:184)
	at net.sf.extjwnl.data.IndexWord$SynsetList.loadSynset(IndexWord.java:408)
	at net.sf.extjwnl.data.IndexWord$SynsetList.loadAllSynsets(IndexWord.java:389)
	at net.sf.extjwnl.data.IndexWord$SynsetList.iterator(IndexWord.java:261)
	at cobra.analytics.wikipedia.batch.Examples.demonstrateSynsets(Examples.java:111)
	at cobra.analytics.wikipedia.batch.Examples.go(Examples.java:68)
	at cobra.analytics.wikipedia.batch.Examples.main(Examples.java:45)
No matter what word I use to try and get the synset of it returns the exception. Here is my file_properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<jwnl_properties language="en">
    <version publisher="Princeton" number="3.1" language="en"/>
    <dictionary class="net.sf.extjwnl.dictionary.FileBackedDictionary">
        <param name="morphological_processor" value="net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor">
            <param name="operations">
                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
                    <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
                    <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
                    <param name="adjective" value="|er=|est=|er=e|est=e|"/>
                    <param name="operations">
                        <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                    </param>
                </param>
                <param value="net.sf.extjwnl.dictionary.morph.TokenizerOperation">
                    <param name="delimiters">
                        <param value=" "/>
                        <param value="-"/>
                    </param>
                    <param name="token_operations">
                        <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
                            <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
                            <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
                            <param name="adjective" value="|er=|est=|er=e|est=e|"/>
                            <param name="operations">
                                <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                            </param>
                        </param>
                    </param>
                </param>
            </param>
        </param>
        <param name="dictionary_element_factory"
               value="net.sf.extjwnl.princeton.data.PrincetonWN17FileDictionaryElementFactory"/>
        <param name="file_manager" value="net.sf.extjwnl.dictionary.file_manager.FileManagerImpl">
            <param name="file_type" value="net.sf.extjwnl.princeton.file.PrincetonRandomAccessDictionaryFile">
                
                
            </param>
            
            <param name="dictionary_path" value="C:\Users\tbuell.CIVOLS\Documents\WordNetFiles\dict\"/>
        </param>
    </dictionary>
    <resource class="net.sf.extjwnl.princeton.PrincetonResource"/>
</jwnl_properties>

**Comment by autayeu** [comment]
The property file is empty or was not pasted properly. To escape it, you can use syntax like this:

\`\`\`xml

paste your properties here

\`\`\`


Similar issue with the code. To escape the code properly, you can use syntax like this:

\`\`\`java

paste your code here

\`\`\`


You can also use "Preview" tab in the comment window to check that your code and properties render correctly.

Please, update. Thank you!

**Comment by tbuell26** [comment]
Maybe it would be easier if I attach the files.
Here is the java file.
[Examples.txt](https://github.com/extjwnl/extjwnl/files/607409/Examples.txt)

Here is the file-properties.xml(I saved it as txt file so I could attach it)
[file_properties.txt](https://github.com/extjwnl/extjwnl/files/607425/file_properties.txt)

**Comment by autayeu** [comment]
It's working. Here is the output I'm getting with your files:
```
 The gloss is arousing or provoking laughter; "an amusing film with a steady stream of pranks and pratfalls"; "an amusing fellow"; "a comic hat"; "a comical look of surprise"; "funny stories that made everybody laugh"; "a very funny writer"; "it would have been laughable if it hadn't hurt so much"; "a mirthful experience"; "risible courtroom antics"
 The gloss is beyond or deviating from the usual or expected; "a curious hybrid accent"; "her speech has a funny twang"; "they have some funny ideas about war"; "had an odd name"; "the peculiar aromatic odor of cloves"; "something definitely queer about this town"; "what a rum fellow"; "singular behavior"
 The gloss is not as expected; "there was something fishy about the accident"; "up to some funny business"; "some definitely queer goings-on"; "a shady deal"; "her motives were suspect"; "suspicious behavior"
 The gloss is experiencing odd bodily sensations; "told the doctor about the funny sensations in her chest"

```

You've said you're using WordNet 3.1. Where did you get the dictionary files? Are they modified?

**Comment by tbuell26** [comment]
I downloaded the wn3.1.dict.tar.gz file from
https://wordnet.princeton.edu/wordnet/download/current-version/#win. The
link to the download is under the section WordNet 3.1 DATABASE FILES ONLY.
I may have downloaded the wrong file.

**Comment by autayeu** [comment]
No, that's actually correct. I'm using this as well.

Let's go this way - would it be possible for you to create a small standalone project to reproduce the issue, zip it all together (sources+data) and I'll try again to reproduce?
