### ISSUE TITLE
IndexWord.SynsetList doesn't properly support Stream API

### ISSUE THREAD

**Issue by CedricReichenbach** [extjwnl/extjwnl#25]
Streams obtained from `IndexWord.SynsetList` are always empty, even if the list isn't.

The reason is that for other operations, the list is populated lazily by calling `loadAllSynsets()`, but the same isn't the case for `stream()` or `parallelStream()`.

**Comment by autayeu** [comment]
Well noted. Maybe you can fix it and submit a pull request?

**Comment by autayeu** [comment]
I've merged your pull request, tweaked it a bit, added made some maintenance changes and released a 2.0.0. It should be available soon from Maven Central. Thank you for your help.
