### ISSUE TITLE
slf4j logging in user app messed up when using extJWNL

### ISSUE THREAD

**Issue by pasky** [extjwnl/extjwnl#3]
Hi! Somehow, extJWNL interferes with logging in slf4j in my app. Typically, I use something like

-Dorg.slf4j.simpleLogger.log.cz.brmlab.yodaqa=debug

on maven commandline to turn on debug-level logging in my app, but that stops to work when I import extJWNL - some messages from some other 3rd-party modules that I typically don't see start appearing, which is no big deal, but I stop seeing my debug messages. When I revert back to JWNL, things go back to normal.

extJWNL shouldn't affect log levels of the rest of the application.

**Comment by pasky** [comment]
My attempts to reproduce this in fact did fail! I apologize for opening this bug, it must have been some sort of weird interplay with something else... It works fine now. (Or something changed in extJWNL meanwhile which fixed this implicitly. Or maybe it was my transition from Maven to Gradle for application execution. Who knows?)

**Comment by autayeu** [comment]
It would have been better to find out the reason, but thank you anyway for reporting this.
