### ISSUE TITLE
Is extjwnl thread safe?

### ISSUE THREAD

**Issue by jeyendranbalakrishnan** [extjwnl/extjwnl#31]
I need to use access Wordnet (via extJWNL) from different threads.
Can I create one instance per JVM and share the instance reference between threads?
Or do I need to create one instance per thread (in a ThreadLocal) and just accept the increased memory footprint per thread?

Thank you!

**Comment by autayeu** [comment]
It is not formally verified to be thread-safe, but best efforts had been made, some unit tests are present, some bugs had been fixed in the past, so you might give `sharing an instance` approach a try.

**Comment by jeyendranbalakrishnan** [comment]
Thanks for such a quick reply!
I'll try the shared instance approach and post back if I find any issues.
