### ISSUE TITLE
Endless loop on lookup of lemmas with non-english characters.

### ISSUE THREAD

**Issue by younes-abouelnagah** [extjwnl/extjwnl#8]
If you do dict.getIndexWord(POS.NOUN, lemma) with a lemma such as "™" or "â" then the function never returns. It enters in an endless loop at

FileManageImpl.fileGetIndexedLinePointerdict.getIndexWord(pos, lemma)

The problem is that it gets stuck at the end of the file, indefinitely having "offset" equal to "stop - 1".

Thanks for the nice utility. I hope I could help you fix the issue, but I don't know what exactly is going on.

**Comment by autayeu** [comment]
Would you mind sharing some test data to make it easier to reproduce?

**Comment by younes-abouelnagah** [comment]
Wow, that was such a quick response!  I am using a dictionary from a JAR, which I built based on "extjwnl-data-wn31" after adding a few extra words. How can I send it to you?

The initialization code is simply Dictionary.getDefaultResourceInstance();

**Comment by autayeu** [comment]
Just paste that bash script here, I'll repeat it and try reproducing. Which encoding did you use? What is your system (default) locale? Did you edit the config file?

**Comment by younes-abouelnagah** [comment]
I am not sure about the encoding, because I just cloned the extjwnl-data-wn31 repo (https://github.com/extjwnl/extjwnl-data-wn31/tree/master) and used the XML file in its resources (/src/main/resources/extjwnl_resource_properties.xml) as my ewn.xml. The only change I made is that I pointed it to the correct location where the repo was cloned (`<param name="dictionary_path" value="$REPO/src/main/resources/net/sf/extjwnl/data/wordnet/wn31"/>`). Is this the config file you were asking about? If so, then I didn't edit it any further.

My system is an Os X with locale is 
`locale
LANG="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_ALL=
`


Below are a few lines from the script I passed to `ewn --script`. I realized it is too long to be pasted here, but I can send it to you in an e-mail if you want it in its entirety. None of the added words contain non-english letters.. the tokens I look up are sometimes do.

Again, thanks you very much.

`
froot_loops%1:13:99:: -add -addword "froot loop" 
frozen_novelty%1:13:99:: -add -addword "frozen novelties"
fruit_bar%1:13:99:: -add 
fruit_bowl%1:13:99:: -add 
fruit_cup%1:13:99:: -add 
fruit_snack%1:13:99:: -add -addword "fruit snacks"
gala%1:13:99:: -add 

`

**Comment by autayeu** [comment]
Thank you! And how did you add the words with non-English letters?

**Comment by younes-abouelnagah** [comment]
I didn't add any words with non-English letters to the dictionary. The problem happens when I am trying to lookup a word with non-English letters, and instead of returning null the dictionary goes into the infinite loop described. Take "™" for example and look it up; the dictionary will never return.

**Comment by autayeu** [comment]
Ah... got it. Thank you.

**Comment by autayeu** [comment]
I've tried reproducing your lemma search with a default (unedited) resource dictionary and I couldn't.

I've tried editing the dictionary as you've described above and couldn't - actually you can't edit dictionary using resource config file just by changing dictionary_path because PrincetonResourceDictionaryFile won't find load files from file system. You'd need to use file_properties.xml config as base config for your ewn.xml. I wonder how you actually edited the dictionary, but anyway...

I've edited the wn31 dictionary with your script and tried lemma search on the edited dictionary (both as file dictionary and packaged as resource dictionary) - still couldn't reproduce the bug.

At this point I'd need from you a small project which isolates and reproduces the issue. Please, make a small self-contained project, zip it, upload it somewhere and I'll try to take a look at it. Thank you!

**Comment by younes-abouelnagah** [comment]
You are right. when I use the original dictionary JAR the lookups never freeze. I can send you the ewn.xml I use, the WN JAR with the edited dictionary, and anything else you need to solve the problem. However, are we going in the same direction if I do so? I mean, the problem is not with the lookup method, but apparently with the files generated by ewn.. maybe because of the ewn.XML I use?? I believe so, because you say you could edit the dictionary and then do the lookups successfully. Here is the ewn.xml I use

<?xml version="1.0" encoding="UTF-8"?>
<jwnl_properties language="en">
    <version publisher="Princeton" number="3.0" language="en"/>
    <dictionary class="net.sf.extjwnl.dictionary.FileBackedDictionary">
        <param name="morphological_processor" value="net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor">
            <param name="operations">
                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
                    <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
                    <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
                    <param name="adjective" value="|er=|est=|er=e|est=e|"/>
                    <param name="operations">
                        <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                    </param>
                </param>
                <param value="net.sf.extjwnl.dictionary.morph.TokenizerOperation">
                    <param name="delimiters">
                        <param value=" "/>
                        <param value="-"/>
                    </param>
                    <param name="token_operations">
                        <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                        <param value="net.sf.extjwnl.dictionary.morph.DetachSuffixesOperation">
                            <param name="noun" value="|s=|ses=s|xes=x|zes=z|ches=ch|shes=sh|men=man|ies=y|"/>
                            <param name="verb" value="|s=|ies=y|es=e|es=|ed=e|ed=|ing=e|ing=|"/>
                            <param name="adjective" value="|er=|est=|er=e|est=e|"/>
                            <param name="operations">
                                <param value="net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation"/>
                                <param value="net.sf.extjwnl.dictionary.morph.LookupExceptionsOperation"/>
                            </param>
                        </param>
                    </param>
                </param>
            </param>
        </param>
        <param name="dictionary_element_factory"
               value="net.sf.extjwnl.princeton.data.PrincetonWN17FileDictionaryElementFactory"/>
        <param name="file_manager" value="net.sf.extjwnl.dictionary.file_manager.FileManagerImpl">
            <param name="file_type" value="net.sf.extjwnl.princeton.file.PrincetonRandomAccessDictionaryFile">
                
                
            </param>
            
            <param name="dictionary_path" value="../src/main/resources/net/sf/extjwnl/data/wordnet/wn31"/>
        </param>
    </dictionary>
    <resource class="net.sf.extjwnl.princeton.PrincetonResource"/>
</jwnl_properties>

**Comment by younes-abouelnagah** [comment]
Can it be something to do with the line ending styles?

**Comment by autayeu** [comment]
ewn.xml looks right. Line endings should be unix, I recall struggling with this due to git autocrlf behaviour. But the repo should have line settings fixed to unix, so if you clone the dictionary repo and edit, it should be fine.

We can try this. You can try redoing from scratch - clone the dict repo, edit it again with ewn and your script, make a jar and try. Afterall, I was able to edit the dictionary using (part of) your script and it worked.

And I can try this - upload somewhere the dictionary jar which shows the bug. I'll look at it and try to reproduce the bug again. It's interesting to figure that out anyway. Thank you.

**Comment by younes-abouelnagah** [comment]
OK.. I will do that. Thank you.

**Comment by younes-abouelnagah** [comment]
I created a ticket on Sourceforge and attached the JAR to it: https://sourceforge.net/p/extjwnl/tickets/10/

Looking forward for your insights. Thank you very much!

**Comment by autayeu** [comment]
Thank you. I've got your dictionary jar and still can't reproduce :(  Here is the piece of code I use:
```java
        String lemma = "™";
        IndexWord iw = dic.getIndexWord(POS.NOUN, lemma);
        assertThat(iw, is(nullValue()));
        lemma = "â";
        iw = dic.getIndexWord(POS.NOUN, lemma);
        assertThat(iw, is(nullValue()));
        lemma = "zywiec";
        iw = dic.getIndexWord(POS.NOUN, lemma);
        assertThat(iw, is(nullValue()));
```

I've tried also newly added words and they've been found. 

Nevertheless, there are a few strange things in the dictionary:
* entrées contains one non-ASCII char - so it's unsafe to rely on default encoding.
* a few quoted words like "anitpasti". I don't know why or what for you need to quote them, but maybe you need that for some reason.
* cntlist isn't sorted properly - that might be a different bug.

Look, lets go for a small standalone project. Can you make a small standalone project to reproduce the bug? I'll run it and try again.

**Comment by autayeu** [comment]
I've fixed cntlist sorting. Lets figure out this lookup one.

**Comment by younes-abouelnagah** [comment]
Thanks for pointing out the strange things in the dictionary. I will work on fixing them, but this shouldn't be causing the problem specially that it doesn't happen on your machine. 

I created a standalone project showing the problem.. at least on my Mac. See https://sourceforge.net/p/extjwnl/tickets/10/. Thanks again.

**Comment by autayeu** [comment]
Thank you for the project! I'll try taking a look next week, hopefully in the beginning.

**Comment by autayeu** [comment]
I took a look at your project, but not every Java developer has Scala stack ;) I can't run your project - I have no Scala stack. Can you make a Java one? And by the way, there were two projects there one inside another. Probably only one is needed.

To speed things up, you can try https://github.com/autayeu/extjwnl/tree/blockreads branch. It's going to be a next version - it's faster and uses less memory in some cases. It's been refactored. There is a test there ```TestLemmasLookup.java```, it tries to reproduce your situation.

**Comment by younes-abouelnagah** [comment]
Thank you very much. I had attached the JAR to the SourceForge issue so
that you don't need to build the project, as I expected you might not have
SBT installed. Could yo please try running that JAR?

I don't have Maven installed. I will install Maven and create a Java
project as soon as possible, but I am a bit pressed on time these days. I
don't know of any other was I can create a Java project that would compile
on two different machines.

Thanks for pointing out the blockreads branch.. I will give it a shot. Is
it stable?

    <http://corp.flipp.com>

Younes Abouelnagah
Sr. Data Science Engineer
Flipp Corporation

p: 416-668-3423
e: younes.abouelnagah@flipp.com

On Tue, Jun 16, 2015 at 4:08 PM, Aliaksandr Autayeu <
notifications@github.com> wrote:

> I took a look at your project, but not every Java developer has Scala
> stack ;) I can't run your project - I have no Scala stack. Can you make a
> Java one? And by the way, there were two projects there one inside another.
> Probably only one is needed.
>
> To speed things up, you can try
> https://github.com/autayeu/extjwnl/tree/blockreads branch. It's going to
> be a next version - it's faster and uses less memory in some cases. It's
> been refactored. There is a test there TestLemmasLookup.java, it tries to
> reproduce your situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/extjwnl/extjwnl/issues/8#issuecomment-112553042>.
>

-- 
IMPORTANT NOTICE:  This message, including any attachments (hereinafter 
collectively referred to as "Communication"), is intended only for the addressee(s) 
named above.  This Communication may include information that is 
privileged, confidential and exempt from disclosure under applicable law. 
 If the recipient of this Communication is not the intended recipient, or 
the employee or agent responsible for delivering this Communication to the 
intended recipient, you are notified that any dissemination, distribution 
or copying of this Communication is strictly prohibited.  If you have 
received this Communication in error, please notify the sender immediately 
by phone or email and permanently delete this Communication from your 
computer without making a copy. Thank you.

**Comment by autayeu** [comment]
You don't need Maven. Plain java file with ```public static void main...``` and a shell script along the lines of 
```
javac TestBlaBla.java
java -cp .;extjwnl-version.jar;dict-data-version.jar TestBlaBla
```
is much simpler and is enough.

**Comment by autayeu** [comment]
Hi! Any news on this?

**Comment by younes-abouelnagah** [comment]
Hi. Here is the translation of the Scala code into Java:

```
import net.sf.extjwnl.data.IndexWord;
import net.sf.extjwnl.data.POS;
import net.sf.extjwnl.dictionary.Dictionary;

/**
 * Pass in the words you want to lookup as CLI args.
 */
public class ExtJwnlEndlessLoopCLI {

    public static void main(String[] args) throws Exception {
        Dictionary dict = Dictionary.getDefaultResourceInstance();

        for (String lemma: args) {
            IndexWord wnWordOpt = dict.getIndexWord(POS.NOUN, lemma);
            String wnLemma = null;
            if (wnWordOpt != null) {
                wnLemma = wnWordOpt.getLemma();
            } else {
                IndexWord wnBFOpt = dict.getMorphologicalProcessor().lookupBaseForm(POS.NOUN, lemma);
                if (wnBFOpt != null) {
                    wnLemma = wnBFOpt.getLemma();
                } else {
                    wnLemma = "NOT FOUND";
                }
            }

            System.out.println(lemma + " = " + wnLemma);
        }
    }

}
```

I couldn't run it because I don't know how to manually do dependency management. I have all the dependencies needed in a lib folder next to the Java file, but it seems I need to specify them one by on in the -cp flag. For example, the run will fail with java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory. Anyway, I figured you can copy paste the Java class into your own IDE and run it.

**Comment by younes-abouelnagah** [comment]
I have copied the class into an IDE project with the required dependencies and I verified that it does reproduce the problem. The endless loop happens for all of "™ â zywiec", but not other words (that is the program works in most cases). The environment is a Mac with java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by autayeu** [comment]
I've tried the jar. I can't reproduce it in Windows, because of the encoding in Windows console (it's not UTF) - it just gets ™ as ? and gives NOT FOUND:
```cmd
...\ExtJwnlEndlessLoop>java -jar ExtJWnlEndlessLoop.jar good zywiec ™ â zywiec™
good = good
zywiec = NOT FOUND
? = NOT FOUND
a = a
zywiec? = NOT FOUND
```

I've tried from source code in IDE, like this:
```java
    public void testLookups() throws JWNLException {
        dic = Dictionary.getDefaultResourceInstance();
        String[] args = {"™", "â", "zywiec"};
        for (String lemma : args) {
            IndexWord wnWordOpt = dic.getIndexWord(POS.NOUN, lemma);
            assertNull(wnWordOpt);
            IndexWord wnBFOpt = dic.getMorphologicalProcessor().lookupBaseForm(POS.NOUN, lemma);
            assertNull(wnBFOpt);
        }
    }
```
and again, it works in Windows.

I've installed Ubuntu and tried it there - and there is hangs. Finally :)

So, the difference is that this line
```java
buffer = Charset.defaultCharset().newDecoder().decode(ByteBuffer.wrap(output.toByteArray()));
```
returns a buffer with different limits: 4798402 on Linux and 4798403 on Windows. Capacity is 4798403 in both cases. So, it's an off-by-one somewhere in Java. I didn't dig deeper into decoders to understand why this happens.

In the new blockreads branch line reads and binary search parts are written in a more robust way and there it works. I'll be merging and releasing it soon, so that you can use it. However, apart from this bug, I recommend you redo your dictionary by rerunning ewn with your script using ewn from new release, because there were some dictionary editing bugs fixed.

**Comment by autayeu** [comment]
You can use 1.9 - I've published it to Sonatype and it should be synced soon to Maven Central. It should work, but a confirmation from you would be nice :)

**Comment by younes-abouelnagah** [comment]
I am using Version 1.9 now, and things seem to work on my dev machine. Thank you very much for the support.

**Comment by autayeu** [comment]
Sounds great :) You're welcome :)
